# Generated by Django 4.2.6 on 2024-01-03 13:42

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "type_utilisateur",
                    models.CharField(
                        choices=[
                            ("etudiant", "Etudiant"),
                            ("enseignant", "Enseignant"),
                            ("secretaire", "Secrétaire"),
                        ],
                        default="etudiant",
                        max_length=10,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Contrat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("titre", models.CharField(max_length=100, null=True)),
                ("description", models.TextField()),
                ("competences", models.TextField(null=True)),
                ("etat", models.CharField(max_length=50, null=True)),
                ("gratification", models.CharField(max_length=50, null=True)),
                ("dateDeb", models.DateField()),
                ("dateFin", models.DateField()),
                ("estValide", models.BooleanField(null=True)),
                ("enFrance", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomDep", models.CharField(max_length=100)),
                ("adresseDep", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "numSiret",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("numSiren", models.CharField(max_length=100, null=True, unique=True)),
                ("nomEnt", models.CharField(max_length=50)),
                ("mailEnt", models.EmailField(max_length=100, null=True)),
                ("codeNaf", models.CharField(max_length=50, null=True)),
                ("adresseEnt", models.CharField(max_length=255)),
                ("cpEnt", models.IntegerField()),
                ("villeEnt", models.CharField(max_length=100)),
                ("formeJuridique", models.CharField(max_length=100, null=True)),
                ("telEnt", models.CharField(max_length=25, null=True)),
                ("siteWeb", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Etablissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomUniversite", models.CharField(max_length=100)),
                ("adresseUniversite", models.CharField(max_length=255)),
                ("cpEtablissement", models.IntegerField()),
                ("villeEtablissement", models.CharField(max_length=100)),
                ("telEtablissement", models.CharField(max_length=25)),
                ("mailEtablissement", models.EmailField(max_length=100)),
                ("siretEtablissement", models.CharField(max_length=100)),
                ("adresseEtablissement", models.CharField(max_length=255)),
                ("nomEtablissement", models.CharField(max_length=100)),
                ("directeurEtablissement", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProfilEnseignant",
            fields=[
                (
                    "numHarpege",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nomEnseignant", models.CharField(max_length=50, null=True)),
                ("prenomEnseignant", models.CharField(max_length=50, null=True)),
                ("telEnseignant", models.CharField(max_length=25, null=True)),
                ("mailEnseignant", models.EmailField(max_length=100, null=True)),
                (
                    "roleEnseignant",
                    models.CharField(
                        choices=[
                            ("chef_departement", "Chef de Département"),
                            ("enseignant_normal", "Enseignant Normal"),
                            ("enseignant_promo", "Enseignant de Promo"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("disciplineEnseignant", models.CharField(max_length=150, null=True)),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomTheme", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Tuteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomTuteur", models.CharField(max_length=50)),
                ("prenomTuteur", models.CharField(max_length=50)),
                ("metierTuteur", models.CharField(default="", max_length=50)),
                ("telTuteur", models.CharField(max_length=25, null=True)),
                ("emailTuteur", models.EmailField(max_length=100)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.entreprise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Soutenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateSoutenance", models.DateField()),
                ("heureSoutenance", models.TimeField()),
                ("estDistanciel", models.BooleanField()),
                (
                    "candide",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.profilenseignant",
                    ),
                ),
                (
                    "idContrat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.contrat",
                    ),
                ),
                (
                    "salle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.salle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Responsable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomResp", models.CharField(max_length=50)),
                ("prenomResp", models.CharField(max_length=50)),
                ("emailResp", models.EmailField(max_length=100)),
                ("posteResp", models.CharField(max_length=50, null=True)),
                ("telResp", models.CharField(max_length=25, null=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.entreprise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomPromo", models.CharField(max_length=100)),
                ("anneeScolaire", models.CharField(max_length=100)),
                ("parcours", models.CharField(max_length=100, null=True)),
                ("volumeHoraire", models.FloatField(null=True)),
                (
                    "departement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lesApprentiStage.departement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfilSecretaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numSec", models.CharField(max_length=20, null=True)),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfilEtudiant",
            fields=[
                ("nomEtu", models.CharField(max_length=50, null=True)),
                ("prenomEtu", models.CharField(max_length=50, null=True)),
                ("prenom2Etu", models.CharField(max_length=50, null=True)),
                (
                    "numEtu",
                    models.CharField(max_length=35, primary_key=True, serialize=False),
                ),
                ("civiliteEtu", models.CharField(max_length=5, null=True)),
                ("adresseEtu", models.CharField(max_length=255, null=True)),
                ("mailEtu", models.EmailField(max_length=255, null=True)),
                ("telEtu", models.CharField(max_length=25, null=True)),
                ("dateNEtu", models.DateField(null=True)),
                ("lieuNEtu", models.CharField(max_length=100, null=True)),
                ("departementNEtu", models.CharField(max_length=100, null=True)),
                ("nationaliteEtu", models.CharField(max_length=100, null=True)),
                ("numDossier", models.IntegerField(null=True)),
                ("ineEtu", models.IntegerField(null=True)),
                ("cpEtu", models.IntegerField(null=True)),
                ("villeEtu", models.CharField(max_length=100, null=True)),
                ("adresseParent", models.CharField(max_length=255, null=True)),
                ("cpParent", models.IntegerField(null=True)),
                ("villeParent", models.CharField(max_length=100, null=True)),
                ("telParent", models.CharField(max_length=25, null=True)),
                ("mailParent", models.EmailField(max_length=100, null=True)),
                ("remarques", models.TextField(null=True)),
                (
                    "idDepartement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.departement",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lesApprentiStage.promo",
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("mailRh", models.EmailField(max_length=100)),
                ("competences", models.TextField()),
                ("duree", models.CharField(max_length=50)),
                ("datePublication", models.DateField()),
                ("estPublie", models.BooleanField(default=False)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.entreprise",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.theme",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.DecimalField(decimal_places=2, max_digits=4)),
                ("commentaire", models.TextField()),
                (
                    "contrat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.contrat",
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.profilenseignant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnseignantPromo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.profilenseignant",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.promo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("fichier", models.FileField(upload_to="documents/")),
                (
                    "contrat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.contrat",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="departement",
            name="chef",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lesApprentiStage.profilenseignant",
            ),
        ),
        migrations.AddField(
            model_name="contrat",
            name="enseignant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lesApprentiStage.profilenseignant",
            ),
        ),
        migrations.AddField(
            model_name="contrat",
            name="entreprise",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lesApprentiStage.entreprise",
            ),
        ),
        migrations.AddField(
            model_name="contrat",
            name="etudiant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="lesApprentiStage.profiletudiant",
            ),
        ),
        migrations.AddField(
            model_name="contrat",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lesApprentiStage.theme"
            ),
        ),
        migrations.AddField(
            model_name="contrat",
            name="tuteur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lesApprentiStage.tuteur",
            ),
        ),
        migrations.CreateModel(
            name="NombreSoutenances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreSoutenancesStage", models.PositiveIntegerField(default=0)),
                (
                    "nombreSoutenancesApprentissage",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.profilenseignant",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.promo",
                    ),
                ),
            ],
            options={
                "unique_together": {("enseignant", "promo")},
            },
        ),
    ]
