# Generated by Django 4.2.7 on 2023-11-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesApprentiStage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soutenance',
            name='date',
        ),
    ]
