# Generated by Django 4.2.7 on 2023-12-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesApprentiStage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUniversite', models.CharField(max_length=100)),
                ('adresseUniversite', models.CharField(max_length=255)),
                ('cpEtablissement', models.IntegerField()),
                ('villeEtablissement', models.CharField(max_length=100)),
                ('telEtablissement', models.CharField(max_length=25)),
                ('mailEtablissement', models.EmailField(max_length=100)),
                ('siretEtablissement', models.CharField(max_length=100)),
                ('adresseEtablissement', models.CharField(max_length=255)),
                ('nomEtablissement', models.CharField(max_length=100)),
                ('directeurEtablissement', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='contrat',
            name='competences',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='titre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='codeNaf',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='formeJuridique',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='mailEnt',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='numSiren',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='siteWeb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='telEnt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profilenseignant',
            name='disciplineEnseignant',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profilenseignant',
            name='telEnseignant',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='adresseParent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='cpParent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='dateNEtu',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='departementNEtu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='ineEtu',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='lieuNEtu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='mailEtu',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='mailParent',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='nationaliteEtu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='numDossier',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='prenom2Etu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='remarques',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='telParent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='villeParent',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='parcours',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='volumeHoraire',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='responsable',
            name='posteResp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='responsable',
            name='telResp',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='mailRh',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tuteur',
            name='telTuteur',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
