# Generated by Django 4.2.6 on 2023-10-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesApprentiStage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilsecretaire",
            name="numSec",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
