# Generated by Django 4.2.6 on 2023-10-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesApprentiStage', '0003_remove_etudiant_profil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSoutenance', models.DateField()),
                ('heureSoutenance', models.TimeField()),
                ('estDistanciel', models.BooleanField()),
                ('candide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesApprentiStage.profilenseignant')),
                ('idContrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesApprentiStage.contrat')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesApprentiStage.salle')),
            ],
        ),
    ]
