# Generated by Django 4.2.6 on 2023-10-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lesApprentiStage", "0003_remove_etudiant_profil_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="entreprise",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lesApprentiStage.entreprise",
            ),
        ),
    ]
