# Generated by Django 4.2.6 on 2023-12-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesApprentiStage", "0003_alter_entreprise_telent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrat",
            name="estValide",
            field=models.BooleanField(null=True),
        ),
    ]
