# Generated by Django 4.2.6 on 2023-10-25 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesApprentiStage', '0004_salle_soutenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='candide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesApprentiStage.profilenseignant'),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='idContrat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesApprentiStage.contrat'),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesApprentiStage.salle'),
        ),
    ]
