# Generated by Django 4.2.6 on 2023-12-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesApprentiStage", "0004_alter_contrat_estvalide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrat",
            name="etat",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
