# Generated by Django 4.2.6 on 2023-10-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesApprentiStage", "0004_contrat_entreprise"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="estValide",
            field=models.BooleanField(default=False),
        ),
    ]
