# Generated by Django 5.0 on 2023-12-18 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesApprentiStage', '0005_alter_contrat_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreSoutenances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSoutenances', models.PositiveIntegerField(default=0)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesApprentiStage.profilenseignant')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesApprentiStage.promo')),
            ],
            options={
                'unique_together': {('enseignant', 'promo')},
            },
        ),
    ]
