# Generated by Django 4.2.6 on 2023-10-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lesApprentiStage", "0006_alter_contrat_enseignant_alter_contrat_tuteur"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="enFrance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contrat",
            name="gratification",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tuteur",
            name="metierTuteur",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="numSiret",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.DecimalField(decimal_places=2, max_digits=4)),
                ("commentaire", models.TextField()),
                (
                    "contrat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.contrat",
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.profilenseignant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("fichier", models.FileField(upload_to="documents/")),
                (
                    "contrat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesApprentiStage.contrat",
                    ),
                ),
            ],
        ),
    ]
