# Generated by Django 5.0 on 2023-12-18 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesApprentiStage', '0006_nombresoutenances'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilenseignant',
            name='nombre_soutenances',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesApprentiStage.nombresoutenances'),
        ),
    ]
