# Generated by Django 4.2.6 on 2023-10-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesApprentiStage", "0007_contrat_enfrance_contrat_gratification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrat",
            name="enFrance",
            field=models.BooleanField(default=True),
        ),
    ]
