# Generated by Django 5.0 on 2023-12-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesApprentiStage', '0007_profilenseignant_nombre_soutenances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilenseignant',
            name='nombre_soutenances',
        ),
    ]
