# Generated by Django 4.2.6 on 2023-10-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesApprentiStage', '0008_alter_contrat_enfrance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='offre',
        ),
    ]
