# Generated by Django 5.0 on 2023-12-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesApprentiStage', '0008_remove_profilenseignant_nombre_soutenances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='annee',
        ),
        migrations.AddField(
            model_name='promo',
            name='anneScolaire',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
