# Generated by Django 5.0 on 2023-12-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesApprentiStage', '0009_remove_promo_annee_promo_annescolaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='anneScolaire',
            new_name='anneeScolaire',
        ),
    ]
