# Generated by Django 4.2.6 on 2023-11-06 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("lesApprentiStage", "0009_remove_contrat_offre"),
    ]

    operations = [
        migrations.AddField(
            model_name="offre",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
