# Generated by Django 5.0 on 2023-12-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesApprentiStage', '0010_rename_annescolaire_promo_anneescolaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='volumeHoraire',
            field=models.FloatField(null=True),
        ),
    ]
