# Generated by Django 4.2.6 on 2023-11-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesApprentiStage", "0010_offre_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="offre",
            name="mailRh",
            field=models.TextField(default="mail@gmail.com"),
            preserve_default=False,
        ),
    ]
