# Generated by Django 5.0 on 2023-12-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesApprentiStage', '0011_alter_promo_volumehoraire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nombresoutenances',
            old_name='nombreSoutenances',
            new_name='nombreSoutenancesApprentissage',
        ),
        migrations.AddField(
            model_name='nombresoutenances',
            name='nombreSoutenancesStagiaire',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
